object FormSelect: TFormSelect
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'FormSelect'
  ClientHeight = 196
  ClientWidth = 248
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poOwnerFormCenter
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 1
    Top = 1
    Width = 247
    Height = 194
    BevelWidth = 2
    Caption = 'Panel1'
    ShowCaption = False
    TabOrder = 0
    object SpeedButton1: TSpeedButton
      Left = 3
      Top = 155
      Width = 241
      Height = 36
      Caption = #1055#1088#1080#1084#1077#1085#1080#1090#1100
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      OnClick = SpeedButton1Click
    end
    object Item_ListBox: TListBox
      Left = 3
      Top = 3
      Width = 241
      Height = 152
      ItemHeight = 13
      MultiSelect = True
      TabOrder = 0
    end
  end
end
